[buildPlans.iosevka-solid]
family = "Iosevka Solid"
spacing = "normal"
serifs = "sans"
export-glyph-names = false
noCvSs = true
noLigation = true

[buildPlans.iosevka-solid.variants]
inherits = "ss08"

[buildPlans.iosevka-solid.variants.design]
capital-a = "curly-serifless"
capital-d = "more-rounded-serifless"
capital-f = "serifless"
capital-g = "toothed-serifless-capped"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-q = "crossing"
capital-r = "curly-serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
f = "serifless"
g = "double-storey-open"
i = "serifed-flat-tailed"
j = "serifed"
l = "serifed-flat-tailed"
m = "short-leg-serifless"
v = "straight-serifless"
y = "curly-serifless"
eszet = "longs-s-lig-serifless"
lower-delta = "rounded"
capital-gamma = "serifless"
lower-lambda = "straight-turn"
lower-mu = "tailed-serifless"
zero = "slashed"
one = "base"
two = "straight-neck-serifless"
four = "semi-open-serifless"
six = "open-contour"
seven = "bend-serifless"
eight = "crossing"
nine = "open-contour"
tilde = "low"
asterisk = "penta-low"
underscore = "low"
caret = "medium"
paren = "normal"
brace = "curly"
number-sign = "upright"
ampersand = "upper-open"
at = "threefold"
dollar = "through-cap"
percent = "rings-segmented-slash"
bar = "natural-slope"
lig-ltgteq = "slanted"
punctuation-dot = "round"
diacritic-dot = "round"

[buildPlans.iosevka-solid.variants.italic]
two = "curly-neck-serifless"
four = "closed-serifless"
six = "closed-contour"
nine = "closed-contour"

[buildPlans.iosevka-solid.metricOverride]
leading = 1500
