[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
# no-cv-ss = true

[buildPlans.iosevka-custom.variants]
inherits = "ss08"

[buildPlans.iosevka-custom.variants.design]
capital-a = "curly-serifless"
capital-d = "more-rounded-serifless"
capital-f = "serifless"
capital-g = "toothed-serifless-capped"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-m = "hanging"
capital-n = "standard"
capital-q = "crossing"
capital-r = "curly"
capital-u = "toothless-rounded"
capital-v = "straight"
capital-z = "straight-serifless"
a = "double-storey-serifless"
f = "serifless"
g = "double-storey-open"
i = "serifed-flat-tailed"
j = "serifed"
l = "serifed-flat-tailed"
m = "short-leg"
v = "straight"
y = "curly"
eszet = "longs-s-lig"
turn-v = "straight"
lower-delta = "rounded"
capital-gamma = "serifless"
lower-lambda = "straight-turn"
lower-mu = "tailed"
zero = "slashed"
one = "base"
two = "curly-neck"
four = "closed"
six = "open-contour"
seven = "bend-serifless"
eight = "crossing"
nine = "open-contour"
tilde = "low"
asterisk = "penta-low"
underscore = "low"
caret = "medium"
paren = "normal"
brace = "curly"
number-sign = "upright"
ampersand = "upper-open"
at = "threefold"
dollar = "through-cap"
percent = "rings-segmented-slash"
bar = "natural-slope"
lig-ltgteq = "slanted"
punctuation-dot = "round"
diacritic-dot = "round"

[buildPlans.iosevka-custom.ligations]
inherits = "haskell"

[buildPlans.iosevka-custom.metric-override]
leading = 1400

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57600 # 0xe100
featureTag = 'XALL'
sequence = "<->"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57601 # 0xe101
featureTag = 'XALL'
sequence = "<-->"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57605 # 0xe105
featureTag = 'XALL'
sequence = "<=>"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57606 # 0xe106
featureTag = 'XALL'
sequence = "<==>"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57655 # 0xe137
featureTag = 'XALL'
sequence = "<-"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57657 # 0xe139
featureTag = 'XALL'
sequence = "->"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57670 # 0xe146
featureTag = 'XALL'
sequence = "::"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57676 # 0xe14c
featureTag = 'XALL'
sequence = "->>"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57682 # 0xe152
featureTag = 'XALL'
sequence = "-->"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57685 # 0xe155
featureTag = 'XALL'
sequence = "-->>"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57697 # 0xe161
featureTag = 'XALL'
sequence = "=>"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57706 # 0xe16a
featureTag = 'XALL'
sequence = "==>"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57730 # 0xe182
featureTag = 'XALL'
sequence = "<--"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57745 # 0xe191
featureTag = 'XALL'
sequence = "<="

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57754 # 0xe19a
featureTag = 'XALL'
sequence = "<=="

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57769 # 0xe1a9
featureTag = 'XALL'
sequence = ">=>"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57770 # 0xe1aa
featureTag = 'XALL'
sequence = ">->"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57771 # 0xe1ab
featureTag = 'XALL'
sequence = ">-->"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57772 # 0xe1ac
featureTag = 'XALL'
sequence = ">==>"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57773 # 0xe1ad
featureTag = 'XALL'
sequence = "<=<"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57774 # 0xe1ae
featureTag = 'XALL'
sequence = "<-<"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57775 # 0xe1af
featureTag = 'XALL'
sequence = "<--<"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57776 # 0xe1b0
featureTag = 'XALL'
sequence = "<==<"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57783 # 0xe1b7
featureTag = 'XALL'
sequence = ":="

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57786 # 0xe1ba
featureTag = 'XALL'
sequence = "=:"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57797 # 0xe1c5
featureTag = 'XALL'
sequence = "/="

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57799 # 0xe1c7
featureTag = 'XALL'
sequence = "/\\"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57800 # 0xe1c8
featureTag = 'XALL'
sequence = "\\/"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57805 # 0xe1cc
featureTag = 'XALL'
sequence = ">~>"

[[buildPlans.iosevka-custom.compatibility-ligatures]]
unicode = 57806 # 0xe1cc
featureTag = 'XALL'
sequence = "<~>"
