[buildPlans.iosevka-solid]
family = "Iosevka Solid"
spacing = "normal"
serifs = "sans"
export-glyph-names = false
noCvSs = true
noLigation = true

[buildPlans.iosevka-solid.variants]
inherits = "ss15"

[buildPlans.iosevka-solid.variants.design]
apl-form = "enable"
capital-a = "curly-serifless"
capital-d = "more-rounded-bilateral-serifed"
capital-f = "serifless"
capital-g = "toothed-serifless-capped"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-m = "slanted-sides-hanging-serifless"
capital-n = "standard-serifless"
capital-q = "crossing"
capital-r = "curly-serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
g = "double-storey-open"
i = "serifed-flat-tailed"
j = "serifed"
l = "serifed-flat-tailed"
m = "short-leg-serifless"
n = "earless-corner-straight-serifless"
p = "eared-serifed"
q = "straight-serifed"
r = "hookless-serifless"
t = "flat-hook"
v = "straight-serifless"
u = "toothless-corner-serifless"
y = "cursive-flat-hook-serifless"
capital-eszet = "rounded-serifless"
eszet = "traditional-flat-hook-descending-middle-serifed"
lower-delta = "rounded"
capital-gamma = "serifless"
lower-lambda = "straight-turn"
lower-mu = "tailed-serifless"
lower-chi = "semi-chancery-straight-serifless"
zero = "slashed"
one = "base"
seven = "bend-serifless"
eight = "crossing"
tilde = "low"
asterisk = "penta-low"
underscore = "low"
caret = "medium"
paren = "normal"
brace = "curly"
number-sign = "upright"
ampersand = "upper-open"
at = "threefold"
dollar = "through-cap"
percent = "rings-segmented-slash"
bar = "natural-slope"
lig-ltgteq = "slanted"
punctuation-dot = "round"
diacritic-dot = "round"

[buildPlans.iosevka-solid.variants.upright]
f = "flat-hook-serifless"
two = "straight-neck-serifless"
four = "semi-open-serifless"
six = "straight-bar"
nine = "straight-bar"

[buildPlans.iosevka-solid.variants.italic]
f = "flat-hook-tailed"
two = "curly-neck-serifless"
four = "closed-serifless"
six = "closed-contour"
nine = "closed-contour"
k = "cursive-serifless"
x = "chancery"

[buildPlans.iosevka-solid.metricOverride]
leading = 1400
